/*
 * test_tables.c - host-side verification of the tables in tables.h.
 *
 * Tests the generated file itself (what the C search and tables.S are built
 * from), not gen_tables.c's memory, so a stale or mis-printed tables.h is
 * caught too.
 *
 *   consistency  every move-table entry equals a fresh quarter_turn on the
 *                cube model; rank/unrank round-trip for every index
 *   moves        entries in range; four quarter turns are the identity
 *   H2           every distance table fully populated, solved entry 0,
 *                no other entry 0, expected maximum and histogram
 *   bfs          each distance entry is 1 + the minimum over its 9
 *                neighbours (checks the table without re-running its BFS)
 *   oracle       exhaustive BFS over all 3,674,160 states; per-depth counts
 *                match the independently known ones (mini.c / solver.c);
 *                diameter 11
 *   H1           h(s) = max(perm_dist, ori_dist) <= d(s) for every state
 *
 * Build:  gcc -O2 -Wall -Wextra -o test_tables test_tables.c
 * Run:    run gen_tables first (it writes tables.h), then test_tables
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "tables.h" /* generated by gen_tables */

/* ---- Cube model ------------------------------------------------------
 * A separate copy of the model in gen_tables.c, used to recompute every
 * move-table entry independently. See gen_tables.c for the full comments.
 */
enum {
    CUBIES = 7,
    PERMUTATIONS = 5040,
    ORIENTATIONS = 729,
    STATES = PERMUTATIONS * ORIENTATIONS,
    FACES = 3,
    UNSEEN = 0xFF,
};

typedef struct {
    uint8_t p[CUBIES], o[CUBIES];
} state_t;

static const uint8_t source[FACES][CUBIES] = {
    {1, 4, 2, 0, 3, 5, 6}, /* R */
    {0, 1, 2, 4, 5, 6, 3}, /* B */
    {0, 2, 5, 3, 1, 4, 6}, /* D */
};
static const uint8_t twist[FACES][CUBIES] = {
    {1, 2, 0, 2, 1, 0, 0},
    {0, 0, 0, 1, 2, 1, 2},
    {0, 0, 0, 0, 0, 0, 0},
};

static state_t quarter_turn(state_t s, int face)
{
    state_t r;
    for (int i = 0; i < CUBIES; ++i) {
        int from = source[face][i];
        r.p[i] = s.p[from];
        r.o[i] = (uint8_t) ((s.o[from] + twist[face][i]) % 3);
    }
    return r;
}

static int perm_index(const state_t *s)
{
    int p = 0;
    for (int i = 0; i < CUBIES; ++i) {
        int smaller = 0;
        for (int j = i + 1; j < CUBIES; ++j)
            smaller += s->p[j] < s->p[i];
        p = p * (CUBIES - i) + smaller;
    }
    return p;
}

static int ori_index(const state_t *s)
{
    int o = 0;
    for (int i = 0; i < 6; ++i)
        o = o * 3 + s->o[i];
    return o;
}

static void unrank(int perm, int ori, state_t *s)
{
    uint8_t available[CUBIES] = {0, 1, 2, 3, 4, 5, 6};
    int f = 720;
    for (int i = 0; i < CUBIES; ++i) {
        int q = perm / f;
        perm %= f;
        s->p[i] = available[q];
        for (int j = q; j + 1 < CUBIES - i; ++j)
            available[j] = available[j + 1];
        if (i < CUBIES - 1)
            f /= CUBIES - 1 - i;
    }
    int sum = 0;
    for (int i = 6; i-- > 0;) {
        s->o[i] = (uint8_t) (ori % 3);
        sum += s->o[i];
        ori /= 3;
    }
    s->o[6] = (uint8_t) ((3 - sum % 3) % 3);
}

/* States at each half-turn distance from solved, 0..11. Obtained by the
 * original BFS in mini.c / solver.c, which uses turn() and rank_state()
 * directly and no transition tables, so it is an independent reference. */
static const long depth_count[12] = {
    1, 9, 54, 321, 1847, 9992, 50136, 227536, 870072, 1887748, 623800, 2644,
};

/* Expected per-distance counts of the two pattern databases. */
static const int perm_hist[] = {1, 9, 54, 297, 1233, 2157, 1244, 45};
static const int ori_hist[] = {1, 2, 12, 64, 274, 336, 40};

static int failures;

static void check(int ok, const char *test, const char *what)
{
    if (!ok) {
        fprintf(stderr, "FAIL [%s] %s\n", test, what);
        failures++;
    }
}

static void pass(const char *test, const char *detail)
{
    printf("PASS [%s] %s\n", test, detail);
}

/* ---- consistency ------------------------------------------------------ */

static void test_consistency(void)
{
    int before = failures;
    state_t s, t;

    for (int p = 0; p < PERMUTATIONS; ++p) {
        unrank(p, 0, &s);
        if (perm_index(&s) != p) {
            check(0, "consistency", "perm unrank/rank round-trip");
            return;
        }
        for (int f = 0; f < FACES; ++f) {
            t = quarter_turn(s, f);
            if (perm_move[f][p] != perm_index(&t)) {
                check(0, "consistency", "perm_move disagrees with cube model");
                return;
            }
        }
    }
    for (int o = 0; o < ORIENTATIONS; ++o) {
        unrank(0, o, &s);
        if (ori_index(&s) != o) {
            check(0, "consistency", "ori unrank/rank round-trip");
            return;
        }
        for (int f = 0; f < FACES; ++f) {
            t = quarter_turn(s, f);
            if (ori_move[f][o] != ori_index(&t)) {
                check(0, "consistency", "ori_move disagrees with cube model");
                return;
            }
        }
    }
    if (failures == before)
        pass("consistency", "move tables match quarter_turn; rank/unrank "
                            "round-trip on all 5040 + 729 indices");
}

/* ---- moves ------------------------------------------------------------ */

/* x -> table[f][x] applied four times must return to x for every x. That
 * also makes each face a bijection (f^3 is its inverse). */
static int four_turns_identity(const uint16_t *table, int n)
{
    for (int f = 0; f < FACES; ++f)
        for (int x0 = 0; x0 < n; ++x0) {
            int x = x0;
            for (int k = 0; k < 4; ++k) {
                x = table[f * n + x];
                if (x >= n)
                    return 0;
            }
            if (x != x0)
                return 0;
        }
    return 1;
}

static void test_moves(void)
{
    int ok_p = four_turns_identity(&perm_move[0][0], PERMUTATIONS);
    int ok_o = four_turns_identity(&ori_move[0][0], ORIENTATIONS);
    check(ok_p, "moves", "perm_move out of range or f^4 != identity");
    check(ok_o, "moves", "ori_move out of range or f^4 != identity");
    if (ok_p && ok_o)
        pass("moves", "all entries in range, f^4 = identity for R, B, D");
}

/* ---- H2 --------------------------------------------------------------- */

static void test_h2(const char *name, const uint8_t *dist, int n,
                    const int *hist_want, int max_want)
{
    int hist[16] = {0}, max = 0, ok = 1;
    for (int i = 0; i < n; ++i) {
        if (dist[i] > 15) { /* UNSEEN or corrupt */
            check(0, "H2", "distance table has an unfilled entry");
            return;
        }
        if (dist[i] > max)
            max = dist[i];
        hist[dist[i]]++;
    }
    ok &= dist[0] == 0;
    check(dist[0] == 0, "H2", "solved entry is not 0");
    for (int i = 1; i < n; ++i)
        if (dist[i] == 0) {
            check(0, "H2", "a non-solved entry has distance 0");
            ok = 0;
            break;
        }
    check(max == max_want, "H2", "unexpected maximum");
    ok &= max == max_want;
    for (int d = 0; d <= max_want; ++d)
        if (hist[d] != hist_want[d]) {
            check(0, "H2", "histogram differs from expected");
            ok = 0;
            break;
        }
    if (ok) {
        char buf[128];
        int len = snprintf(buf, sizeof buf, "%s: %d entries, solved=0, max=%d,"
                                            " histogram", name, n, max);
        for (int d = 0; d <= max && len < (int) sizeof buf - 8; ++d)
            len += snprintf(buf + len, sizeof buf - (size_t) len, " %d",
                            hist[d]);
        pass("H2", buf);
    }
}

/* ---- bfs -------------------------------------------------------------- */

/* A correct BFS distance table satisfies, for every x != 0:
 *   dist[x] == 1 + min over the 9 neighbours y of dist[y]
 * Checked directly, without re-running the BFS that produced it. */
static int bellman_ok(const uint16_t *move, int n, const uint8_t *dist)
{
    for (int x = 1; x < n; ++x) {
        int best = 255;
        for (int f = 0; f < FACES; ++f) {
            int y = x;
            for (int turn = 0; turn < 3; ++turn) {
                y = move[f * n + y];
                if (dist[y] < best)
                    best = dist[y];
            }
        }
        if (dist[x] != best + 1)
            return 0;
    }
    return 1;
}

static void test_bfs(void)
{
    int ok_p = bellman_ok(&perm_move[0][0], PERMUTATIONS, perm_dist);
    int ok_o = bellman_ok(&ori_move[0][0], ORIENTATIONS, ori_dist);
    check(ok_p, "bfs", "perm_dist is not a shortest-path table");
    check(ok_o, "bfs", "ori_dist is not a shortest-path table");
    if (ok_p && ok_o)
        pass("bfs", "every entry = 1 + min over its 9 neighbours");
}

/* ---- oracle and H1 ---------------------------------------------------- */

/* Exhaustive half-turn BFS over the full state space. Returns the exact
 * distance table (caller frees) or NULL. Host-only: never emitted. */
static uint8_t *full_bfs(void)
{
    uint8_t *d = malloc(STATES);
    uint32_t *queue = malloc((size_t) STATES * sizeof *queue);
    if (!d || !queue) {
        free(d);
        free(queue);
        return NULL;
    }
    memset(d, UNSEEN, STATES);
    uint32_t head = 0, tail = 0;
    d[0] = 0;
    queue[tail++] = 0;
    while (head < tail) {
        uint32_t x = queue[head++];
        int p = (int) (x / ORIENTATIONS), o = (int) (x % ORIENTATIONS);
        for (int f = 0; f < FACES; ++f) {
            int np = p, no = o;
            for (int turn = 0; turn < 3; ++turn) {
                np = perm_move[f][np];
                no = ori_move[f][no];
                uint32_t y = (uint32_t) np * ORIENTATIONS + (uint32_t) no;
                if (d[y] == UNSEEN) {
                    d[y] = (uint8_t) (d[x] + 1);
                    queue[tail++] = y;
                }
            }
        }
    }
    free(queue);
    if (tail != STATES) {
        free(d);
        return NULL;
    }
    return d;
}

static void test_oracle(const uint8_t *d)
{
    long count[16] = {0};
    int diameter = 0, ok = 1;
    for (uint32_t s = 0; s < STATES; ++s) {
        count[d[s]]++;
        if (d[s] > diameter)
            diameter = d[s];
    }
    check(diameter == 11, "oracle", "diameter is not 11");
    ok &= diameter == 11;
    for (int k = 0; k < 12; ++k)
        if (count[k] != depth_count[k]) {
            check(0, "oracle", "per-depth state counts differ from mini.c");
            ok = 0;
            break;
        }
    if (ok)
        pass("oracle", "3674160 states reached, diameter 11, per-depth "
                       "counts match mini.c/solver.c");
}

static void test_h1(const uint8_t *d)
{
    long violations = 0, exact = 0;
    double sum_h = 0, sum_d = 0;
    for (uint32_t s = 0; s < STATES; ++s) {
        int p = (int) (s / ORIENTATIONS), o = (int) (s % ORIENTATIONS);
        int h = perm_dist[p] > ori_dist[o] ? perm_dist[p] : ori_dist[o];
        violations += h > d[s];
        exact += h == d[s];
        sum_h += h;
        sum_d += d[s];
    }
    check(violations == 0, "H1", "heuristic overestimates some state");
    if (violations == 0) {
        char buf[160];
        snprintf(buf, sizeof buf,
                 "h <= d on all %d states; mean h %.3f vs mean d %.3f; "
                 "h exact on %ld states",
                 STATES, sum_h / STATES, sum_d / STATES, exact);
        pass("H1", buf);
    } else {
        fprintf(stderr, "      %ld states with h > d\n", violations);
    }
}

int main(void)
{
    test_consistency();
    test_moves();
    test_h2("perm_dist", perm_dist, PERMUTATIONS, perm_hist, 7);
    test_h2("ori_dist", ori_dist, ORIENTATIONS, ori_hist, 6);
    test_bfs();

    uint8_t *d = full_bfs();
    check(d != NULL, "oracle", "BFS did not reach every state (or no memory)");
    if (d) {
        test_oracle(d);
        test_h1(d);
        free(d);
    }

    if (failures) {
        printf("%d check(s) FAILED\n", failures);
        return 1;
    }
    printf("all checks passed\n");
    return 0;
}
